version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - /home/mohammed/Desktop/docker-web:/var/www/html/
        ports:
            - 8000:80
